spring:
  application:
    name: shop-server
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        consumer:
        #来自KafkaBinderConfigurationProperties
        binder:
#          brokers: 192.168.166.182:9092
          #如果需要传递自定义header信息，需要在此处声明，不然自定义消息头是不会出现在最终消息当中的
          #          headers: myType
          configuration:
            auto:
              offset:
                #可以设置原生kafka属性，比如设置新的消费组从最新的offset开始消费
                reset: latest
      bindings:
        #配置自己定义的通道与哪个中间件交互
        shop_input: #ShopChannel里Input和Output的值
          destination: shop_msg #目标主题
        shop_output:
          destination: shop_msg
        order_input:
          destination: order_msg
        order_output:
          destination: order_msg
  kafka:
    bootstrap-servers: 192.168.166.182:9092 #kafka服务地址
    consumer:
      group-id: consumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#      client-id: producer #此处不能加client-id，加上后两个消息队列会出问题
server:
  port: 8100