spring:
  application:
    name: shop-server
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        consumer:
        #来自KafkaBinderConfigurationProperties
        binder:
          brokers: 192.168.166.180:9092
      #配置自己定义的通道与哪个中间件交互
      bindings:
        shop_input: #ShopChannel里Input和Output的值
          destination: shop_msg #目标主题
          group: shop  #多实例时一定要加group
          consumer:
            maxAttempts: 1  #默认3次，1表示禁错误重示
            backOffInitialInterval: 1000  #重试时的回退初始间隔时间
        shop_output:
          destination: shop_msg
        order_input:
          destination: order_msg
          group: order
        order_output:
          destination: order_msg