spring:
  application:
    name: shop-server
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        consumer:
        #来自KafkaBinderConfigurationProperties
        binder:
          brokers: 192.168.166.182:9092
          configuration:
            auto:
              offset:
                #可以设置原生kafka属性，比如设置新的消费组从最新的offset开始消费
                reset: latest
      #配置自己定义的通道与哪个中间件交互
      bindings:
        shop_input: #ShopChannel里Input和Output的值
          destination: shop_msg #目标主题
          group: shop  #多实例时一定要加group
        shop_output:
          destination: shop_msg
        order_input:
          destination: order_msg
        order_output:
          destination: order_msg